# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.create(name: 'Alabama', link: '/airports/United%20States/Alabama')
Location.create(name: 'American Samoa', link: '/airports/United%20States/American%20Samoa')
Location.create(name: 'Arizona', link: '/airports/United%20States/Arizona')
Location.create(name: 'Arkansas', link: '/airports/United%20States/Arkansas')
Location.create(name: 'California', link: '/airports/United%20States/California')
Location.create(name: 'Colorado', link: '/airports/United%20States/Colorado')
Location.create(name: 'Connecticut', link: '/airports/United%20States/Connecticut')
Location.create(name: 'Delaware', link: '/airports/United%20States/Delaware')
Location.create(name: 'Dist. of Columbia', link: '/airports/United%20States/Dist.%20of%20Columbia')
Location.create(name: 'Florida', link: '/airports/United%20States/Florida')
Location.create(name: 'Georgia', link: '/airports/United%20States/Georgia')
Location.create(name: 'Guam', link: '/airports/United%20States/Guam')
Location.create(name: 'Hawaii', link: '/airports/United%20States/Hawaii')
Location.create(name: 'Idaho', link: '/airports/United%20States/Idaho')
Location.create(name: 'Illinois', link: '/airports/United%20States/Illinois')
Location.create(name: 'Indiana', link: '/airports/United%20States/Indiana')
Location.create(name: 'Iowa', link: '/airports/United%20States/Iowa')
Location.create(name: 'Kansas', link: '/airports/United%20States/Kansas')
Location.create(name: 'Kentucky', link: '/airports/United%20States/Kentucky')
Location.create(name: 'Louisiana', link: '/airports/United%20States/Louisiana')
Location.create(name: 'Maine', link: '/airports/United%20States/Maine')
Location.create(name: 'Maryland', link: '/airports/United%20States/Maryland')
Location.create(name: 'Massachusetts', link: '/airports/United%20States/Massachusetts')
Location.create(name: 'Michigan', link: '/airports/United%20States/Michigan')
Location.create(name: 'Midway Atoll', link: '/airports/United%20States/Midway%20Atoll')
Location.create(name: 'Minnesota', link: '/airports/United%20States/Minnesota')
Location.create(name: 'Mississippi', link: '/airports/United%20States/Mississippi')
Location.create(name: 'Missouri', link: '/airports/United%20States/Missouri')
Location.create(name: 'Montana', link: '/airports/United%20States/Montana')
Location.create(name: 'Nebraska', link: '/airports/United%20States/Nebraska')
Location.create(name: 'Nevada', link: '/airports/United%20States/Nevada')
Location.create(name: 'New Hampshire', link: '/airports/United%20States/New%20Hampshire')
Location.create(name: 'New Jersey', link: '/airports/United%20States/New%20Jersey')
Location.create(name: 'New Mexico', link: '/airports/United%20States/New%20Mexico')
Location.create(name: 'New York', link: '/airports/United%20States/New%20York')
Location.create(name: 'N Mariana Islands', link: '/airports/United%20States/N%20Mariana%20Islands')
Location.create(name: 'North Carolina', link: '/airports/United%20States/North%20Carolina')
Location.create(name: 'North Dakota', link: '/airports/United%20States/North%20Dakota')
Location.create(name: 'Ohio', link: '/airports/United%20States/Ohio')
Location.create(name: 'Oklahoma', link: '/airports/United%20States/Oklahoma')
Location.create(name: 'Oregon', link: '/airports/United%20States/Oregon')
Location.create(name: 'Pennsylvania', link: '/airports/United%20States/Pennsylvania')
Location.create(name: 'Puerto Rico', link: '/airports/United%20States/Puerto%20Rico')
Location.create(name: 'Rhode Island', link: '/airports/United%20States/Rhode%20Island')
Location.create(name: 'South Carolina', link: '/airports/United%20States/South%20Carolina')
Location.create(name: 'South Dakota', link: '/airports/United%20States/South%20Dakota')
Location.create(name: 'Tennessee', link: '/airports/United%20States/Tennessee')
Location.create(name: 'Texas', link: '/airports/United%20States/Texas')
Location.create(name: 'Utah', link: '/airports/United%20States/Utah')
Location.create(name: 'Vermont', link: '/airports/United%20States/Vermont')
Location.create(name: 'Virginia', link: '/airports/United%20States/Virginia')
Location.create(name: 'Virgin Islands', link: '/airports/United%20States/Virgin%20Islands')
Location.create(name: 'Wake Island', link: '/airports/United%20States/Wake%20Island')
Location.create(name: 'Washington', link: '/airports/United%20States/Washington')
Location.create(name: 'West Virginia', link: '/airports/United%20States/West%20Virginia')
Location.create(name: 'Wisconsin', link: '/airports/United%20States/Wisconsin')
Location.create(name: 'Wyoming', link: '/airports/United%20States/Wyoming')
